[project]
name = "PeerChat"
version = "0.6.0"
description = "UDP peer-to-peer messaging library backed by a C networking core. Provides Python bindings for creating sockets, discovering peers via a central synchronization server written in C, and exchanging messages directly between clients without relaying through the server. It leverages a custom made data protocol."
authors = [
    {name = "nizwant", email = "mateusznizwantowski@gmail.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"

dependencies = [
    "cloud-import (>=0.4,<0.5)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)"
]

[dependency-groups]
dev = [
    "numpy (>=2.4.0,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "ipykernel (>=7.1.0,<8.0.0)",
    "pre-commit (>=4.5.1,<5.0.0)"
]


[build-system]
requires = ["setuptools"]
