// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// peer_connect_r
void peer_connect_r(std::string username, std::string password);
RcppExport SEXP _PeerChat_peer_connect_r(SEXP usernameSEXP, SEXP passwordSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type username(usernameSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    peer_connect_r(username, password);
    return R_NilValue;
END_RCPP
}
// peer_get_user_r
void peer_get_user_r(std::string username, std::string password);
RcppExport SEXP _PeerChat_peer_get_user_r(SEXP usernameSEXP, SEXP passwordSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type username(usernameSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    peer_get_user_r(username, password);
    return R_NilValue;
END_RCPP
}
// peer_send_message_r
void peer_send_message_r(std::string recipient, std::string message);
RcppExport SEXP _PeerChat_peer_send_message_r(SEXP recipientSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type recipient(recipientSEXP);
    Rcpp::traits::input_parameter< std::string >::type message(messageSEXP);
    peer_send_message_r(recipient, message);
    return R_NilValue;
END_RCPP
}
// peer_send_ping_r
void peer_send_ping_r(std::string recipient);
RcppExport SEXP _PeerChat_peer_send_ping_r(SEXP recipientSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type recipient(recipientSEXP);
    peer_send_ping_r(recipient);
    return R_NilValue;
END_RCPP
}
// peer_receive_r
int peer_receive_r(int timeout_ms);
RcppExport SEXP _PeerChat_peer_receive_r(SEXP timeout_msSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type timeout_ms(timeout_msSEXP);
    rcpp_result_gen = Rcpp::wrap(peer_receive_r(timeout_ms));
    return rcpp_result_gen;
END_RCPP
}
// peer_disconnect_r
void peer_disconnect_r();
RcppExport SEXP _PeerChat_peer_disconnect_r() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    peer_disconnect_r();
    return R_NilValue;
END_RCPP
}
// peer_get_fd_r
int peer_get_fd_r();
RcppExport SEXP _PeerChat_peer_get_fd_r() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(peer_get_fd_r());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PeerChat_peer_connect_r", (DL_FUNC) &_PeerChat_peer_connect_r, 2},
    {"_PeerChat_peer_get_user_r", (DL_FUNC) &_PeerChat_peer_get_user_r, 2},
    {"_PeerChat_peer_send_message_r", (DL_FUNC) &_PeerChat_peer_send_message_r, 2},
    {"_PeerChat_peer_send_ping_r", (DL_FUNC) &_PeerChat_peer_send_ping_r, 1},
    {"_PeerChat_peer_receive_r", (DL_FUNC) &_PeerChat_peer_receive_r, 1},
    {"_PeerChat_peer_disconnect_r", (DL_FUNC) &_PeerChat_peer_disconnect_r, 0},
    {"_PeerChat_peer_get_fd_r", (DL_FUNC) &_PeerChat_peer_get_fd_r, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_PeerChat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
