# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

peer_connect_r <- function(username, password) {
    invisible(.Call('_PeerChat_peer_connect_r', PACKAGE = 'PeerChat', username, password))
}

peer_get_user_r <- function(username, password) {
    invisible(.Call('_PeerChat_peer_get_user_r', PACKAGE = 'PeerChat', username, password))
}

peer_send_message_r <- function(recipient, message) {
    invisible(.Call('_PeerChat_peer_send_message_r', PACKAGE = 'PeerChat', recipient, message))
}

peer_send_ping_r <- function(recipient) {
    invisible(.Call('_PeerChat_peer_send_ping_r', PACKAGE = 'PeerChat', recipient))
}

peer_receive_r <- function(timeout_ms = 100L) {
    .Call('_PeerChat_peer_receive_r', PACKAGE = 'PeerChat', timeout_ms)
}

peer_disconnect_r <- function() {
    invisible(.Call('_PeerChat_peer_disconnect_r', PACKAGE = 'PeerChat'))
}

peer_get_fd_r <- function() {
    .Call('_PeerChat_peer_get_fd_r', PACKAGE = 'PeerChat')
}

